"""create technologies table

Revision ID: 19cd614f2bce
Revises: 4620b88da880
Create Date: 2026-09-22 14:27:51.947098

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19cd614f2bce"
down_revision: str | Sequence[str] | None = "4620b88da880"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "technologies",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("icon", sa.String(length=255), nullable=True),
        sa.Column("website_url", sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technologies")),
        sa.UniqueConstraint("name", name=op.f("uq_technologies_name")),
    )
    op.create_index(op.f("ix_technologies_slug"), "technologies", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_technologies_slug"), table_name="technologies")
    op.drop_table("technologies")
    # ### end Alembic commands ###
