"""optimized all tables

Revision ID: 3afbe511ff20
Revises: 894da5cf2bfd
Create Date: 2026-09-23 13:04:07.547290

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3afbe511ff20"
down_revision: str | Sequence[str] | None = "894da5cf2bfd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_portfolio_sections_portfolio_id"), table_name="portfolio_sections"
    )
    op.drop_table("portfolio_sections")
    op.drop_index(
        op.f("ix_portfolio_themes_portfolio_id"), table_name="portfolio_themes"
    )
    op.drop_table("portfolio_themes")
    op.drop_index(op.f("ix_blog_post_tags_post_id"), table_name="blog_post_tags")
    op.create_index(
        op.f("ix_blog_post_tags_post_id"), "blog_post_tags", ["post_id"], unique=True
    )
    op.drop_index(op.f("ix_blog_posts_portfolio_id"), table_name="blog_posts")
    op.create_index(
        op.f("ix_blog_posts_portfolio_id"), "blog_posts", ["portfolio_id"], unique=True
    )
    op.create_foreign_key(
        op.f("fk_blog_posts_portfolio_id_portfolios"),
        "blog_posts",
        "portfolios",
        ["portfolio_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "certifications", sa.Column("sort_order", sa.Integer(), nullable=False)
    )
    op.drop_index(op.f("ix_certifications_portfolio_id"), table_name="certifications")
    op.create_index(
        op.f("ix_certifications_portfolio_id"),
        "certifications",
        ["portfolio_id"],
        unique=True,
    )
    op.drop_constraint(
        op.f("fk_certifications_portfolio_id_portfolios"),
        "certifications",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_certifications_portfolio_id_portfolios"),
        "certifications",
        "portfolios",
        ["portfolio_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_contact_messages_portfolio_id"), table_name="contact_messages"
    )
    op.create_index(
        op.f("ix_contact_messages_portfolio_id"),
        "contact_messages",
        ["portfolio_id"],
        unique=True,
    )
    op.drop_index(op.f("ix_educations_portfolio_id"), table_name="educations")
    op.create_index(
        op.f("ix_educations_portfolio_id"), "educations", ["portfolio_id"], unique=True
    )
    op.drop_constraint(
        op.f("fk_educations_portfolio_id_portfolios"), "educations", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_educations_portfolio_id_portfolios"),
        "educations",
        "portfolios",
        ["portfolio_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_experiences_portfolio_id"), table_name="experiences")
    op.create_index(
        op.f("ix_experiences_portfolio_id"),
        "experiences",
        ["portfolio_id"],
        unique=True,
    )
    op.create_foreign_key(
        op.f("fk_experiences_portfolio_id_portfolios"),
        "experiences",
        "portfolios",
        ["portfolio_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_media_assets_portfolio_id"), table_name="media_assets")
    op.create_index(
        op.f("ix_media_assets_portfolio_id"),
        "media_assets",
        ["portfolio_id"],
        unique=True,
    )
    op.drop_constraint(
        op.f("fk_portfolio_seo_portfolio_id_portfolios"),
        "portfolio_seo",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_portfolio_seo_portfolio_id_portfolios"),
        "portfolio_seo",
        "portfolios",
        ["portfolio_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_portfolio_settings_portfolio_id_portfolios"),
        "portfolio_settings",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_portfolio_settings_portfolio_id_portfolios"),
        "portfolio_settings",
        "portfolios",
        ["portfolio_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_portfolios_owner_id"), table_name="portfolios")
    op.create_index(
        op.f("ix_portfolios_owner_id"), "portfolios", ["owner_id"], unique=True
    )
    op.drop_constraint(
        op.f("fk_portfolios_owner_id_users"), "portfolios", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_portfolios_owner_id_users"),
        "portfolios",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("fk_profiles_portfolio_id_portfolios"), "profiles", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_profiles_portfolio_id_portfolios"),
        "profiles",
        "portfolios",
        ["portfolio_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_project_images_project_id"), table_name="project_images")
    op.create_index(
        op.f("ix_project_images_project_id"),
        "project_images",
        ["project_id"],
        unique=True,
    )
    op.drop_index(op.f("ix_project_links_project_id"), table_name="project_links")
    op.create_index(
        op.f("ix_project_links_project_id"),
        "project_links",
        ["project_id"],
        unique=True,
    )
    op.drop_index(
        op.f("ix_project_technologies_project_id"), table_name="project_technologies"
    )
    op.create_index(
        op.f("ix_project_technologies_project_id"),
        "project_technologies",
        ["project_id"],
        unique=True,
    )
    op.drop_index(
        op.f("ix_project_technologies_technology_id"), table_name="project_technologies"
    )
    op.create_index(
        op.f("ix_project_technologies_technology_id"),
        "project_technologies",
        ["technology_id"],
        unique=True,
    )
    op.drop_index(op.f("ix_projects_portfolio_id"), table_name="projects")
    op.create_index(
        op.f("ix_projects_portfolio_id"), "projects", ["portfolio_id"], unique=True
    )
    op.create_foreign_key(
        op.f("fk_projects_portfolio_id_portfolios"),
        "projects",
        "portfolios",
        ["portfolio_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_services_portfolio_id"), table_name="services")
    op.create_index(
        op.f("ix_services_portfolio_id"), "services", ["portfolio_id"], unique=True
    )
    op.drop_index(
        op.f("ix_skill_categories_portfolio_id"), table_name="skill_categories"
    )
    op.create_index(
        op.f("ix_skill_categories_portfolio_id"),
        "skill_categories",
        ["portfolio_id"],
        unique=True,
    )
    op.drop_constraint(
        op.f("fk_skill_categories_portfolio_id_portfolios"),
        "skill_categories",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_skill_categories_portfolio_id_portfolios"),
        "skill_categories",
        "portfolios",
        ["portfolio_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_skills_portfolio_id"), table_name="skills")
    op.create_index(
        op.f("ix_skills_portfolio_id"), "skills", ["portfolio_id"], unique=True
    )
    op.drop_constraint(
        op.f("fk_skills_portfolio_id_portfolios"), "skills", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_skills_portfolio_id_portfolios"),
        "skills",
        "portfolios",
        ["portfolio_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_social_links_portfolio_id"), table_name="social_links")
    op.create_index(
        op.f("ix_social_links_portfolio_id"),
        "social_links",
        ["portfolio_id"],
        unique=True,
    )
    op.drop_constraint(
        op.f("fk_social_links_portfolio_id_portfolios"),
        "social_links",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_social_links_portfolio_id_portfolios"),
        "social_links",
        "portfolios",
        ["portfolio_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_testimonials_portfolio_id"), table_name="testimonials")
    op.create_index(
        op.f("ix_testimonials_portfolio_id"),
        "testimonials",
        ["portfolio_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_testimonials_portfolio_id"), table_name="testimonials")
    op.create_index(
        op.f("ix_testimonials_portfolio_id"),
        "testimonials",
        ["portfolio_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_social_links_portfolio_id_portfolios"),
        "social_links",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_social_links_portfolio_id_portfolios"),
        "social_links",
        "portfolios",
        ["portfolio_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_social_links_portfolio_id"), table_name="social_links")
    op.create_index(
        op.f("ix_social_links_portfolio_id"),
        "social_links",
        ["portfolio_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_skills_portfolio_id_portfolios"), "skills", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_skills_portfolio_id_portfolios"),
        "skills",
        "portfolios",
        ["portfolio_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_skills_portfolio_id"), table_name="skills")
    op.create_index(
        op.f("ix_skills_portfolio_id"), "skills", ["portfolio_id"], unique=False
    )
    op.drop_constraint(
        op.f("fk_skill_categories_portfolio_id_portfolios"),
        "skill_categories",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_skill_categories_portfolio_id_portfolios"),
        "skill_categories",
        "portfolios",
        ["portfolio_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_skill_categories_portfolio_id"), table_name="skill_categories"
    )
    op.create_index(
        op.f("ix_skill_categories_portfolio_id"),
        "skill_categories",
        ["portfolio_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_services_portfolio_id"), table_name="services")
    op.create_index(
        op.f("ix_services_portfolio_id"), "services", ["portfolio_id"], unique=False
    )
    op.drop_constraint(
        op.f("fk_projects_portfolio_id_portfolios"), "projects", type_="foreignkey"
    )
    op.drop_index(op.f("ix_projects_portfolio_id"), table_name="projects")
    op.create_index(
        op.f("ix_projects_portfolio_id"), "projects", ["portfolio_id"], unique=False
    )
    op.drop_index(
        op.f("ix_project_technologies_technology_id"), table_name="project_technologies"
    )
    op.create_index(
        op.f("ix_project_technologies_technology_id"),
        "project_technologies",
        ["technology_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_project_technologies_project_id"), table_name="project_technologies"
    )
    op.create_index(
        op.f("ix_project_technologies_project_id"),
        "project_technologies",
        ["project_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_project_links_project_id"), table_name="project_links")
    op.create_index(
        op.f("ix_project_links_project_id"),
        "project_links",
        ["project_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_project_images_project_id"), table_name="project_images")
    op.create_index(
        op.f("ix_project_images_project_id"),
        "project_images",
        ["project_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_profiles_portfolio_id_portfolios"), "profiles", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_profiles_portfolio_id_portfolios"),
        "profiles",
        "portfolios",
        ["portfolio_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_portfolios_owner_id_users"), "portfolios", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_portfolios_owner_id_users"),
        "portfolios",
        "users",
        ["owner_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_portfolios_owner_id"), table_name="portfolios")
    op.create_index(
        op.f("ix_portfolios_owner_id"), "portfolios", ["owner_id"], unique=False
    )
    op.drop_constraint(
        op.f("fk_portfolio_settings_portfolio_id_portfolios"),
        "portfolio_settings",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_portfolio_settings_portfolio_id_portfolios"),
        "portfolio_settings",
        "portfolios",
        ["portfolio_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_portfolio_seo_portfolio_id_portfolios"),
        "portfolio_seo",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_portfolio_seo_portfolio_id_portfolios"),
        "portfolio_seo",
        "portfolios",
        ["portfolio_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_media_assets_portfolio_id"), table_name="media_assets")
    op.create_index(
        op.f("ix_media_assets_portfolio_id"),
        "media_assets",
        ["portfolio_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_experiences_portfolio_id_portfolios"),
        "experiences",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_experiences_portfolio_id"), table_name="experiences")
    op.create_index(
        op.f("ix_experiences_portfolio_id"),
        "experiences",
        ["portfolio_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_educations_portfolio_id_portfolios"), "educations", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_educations_portfolio_id_portfolios"),
        "educations",
        "portfolios",
        ["portfolio_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_educations_portfolio_id"), table_name="educations")
    op.create_index(
        op.f("ix_educations_portfolio_id"), "educations", ["portfolio_id"], unique=False
    )
    op.drop_index(
        op.f("ix_contact_messages_portfolio_id"), table_name="contact_messages"
    )
    op.create_index(
        op.f("ix_contact_messages_portfolio_id"),
        "contact_messages",
        ["portfolio_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_certifications_portfolio_id_portfolios"),
        "certifications",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_certifications_portfolio_id_portfolios"),
        "certifications",
        "portfolios",
        ["portfolio_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_certifications_portfolio_id"), table_name="certifications")
    op.create_index(
        op.f("ix_certifications_portfolio_id"),
        "certifications",
        ["portfolio_id"],
        unique=False,
    )
    op.drop_column("certifications", "sort_order")
    op.drop_constraint(
        op.f("fk_blog_posts_portfolio_id_portfolios"), "blog_posts", type_="foreignkey"
    )
    op.drop_index(op.f("ix_blog_posts_portfolio_id"), table_name="blog_posts")
    op.create_index(
        op.f("ix_blog_posts_portfolio_id"), "blog_posts", ["portfolio_id"], unique=False
    )
    op.drop_index(op.f("ix_blog_post_tags_post_id"), table_name="blog_post_tags")
    op.create_index(
        op.f("ix_blog_post_tags_post_id"), "blog_post_tags", ["post_id"], unique=False
    )
    op.create_table(
        "portfolio_themes",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("portfolio_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "template", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "primary_color", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "accent_color", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "font_heading", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "font_body", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "config",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_themes_portfolio_id_portfolios"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_themes")),
    )
    op.create_index(
        op.f("ix_portfolio_themes_portfolio_id"),
        "portfolio_themes",
        ["portfolio_id"],
        unique=True,
    )
    op.create_table(
        "portfolio_sections",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("portfolio_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(name="section_type"),
            autoincrement=False,
            nullable=False,
        ),  # type: ignore
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("slug", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("sort_order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "config",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_sections_portfolio_id_portfolios"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_sections")),
    )
    op.create_index(
        op.f("ix_portfolio_sections_portfolio_id"),
        "portfolio_sections",
        ["portfolio_id"],
        unique=True,
    )
    # ### end Alembic commands ###
