"""create skills and skill category table

Revision ID: 4620b88da880
Revises: c89f598d5175
Create Date: 2026-09-22 14:16:57.210409

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4620b88da880"
down_revision: str | Sequence[str] | None = "c89f598d5175"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skill_categories",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_skill_categories_portfolio_id_portfolios"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_categories")),
    )
    op.create_index(
        op.f("ix_skill_categories_portfolio_id"),
        "skill_categories",
        ["portfolio_id"],
        unique=False,
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("proficiency", sa.Integer(), nullable=True),
        sa.Column("years_experience", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["skill_categories.id"],
            name=op.f("fk_skills_category_id_skill_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_skills_portfolio_id_portfolios"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
    )
    op.create_index(
        op.f("ix_skills_category_id"), "skills", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_skills_portfolio_id"), "skills", ["portfolio_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_skills_portfolio_id"), table_name="skills")
    op.drop_index(op.f("ix_skills_category_id"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(
        op.f("ix_skill_categories_portfolio_id"), table_name="skill_categories"
    )
    op.drop_table("skill_categories")
    # ### end Alembic commands ###
