"""create skill category table

Revision ID: 50a82f9a72e2
Revises: 88fbbd7c4236
Create Date: 2026-09-16 14:29:02.075420

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50a82f9a72e2"
down_revision: str | Sequence[str] | None = "88fbbd7c4236"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skill_categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_skill_categories_name")),
    )
    op.add_column("skills", sa.Column("category_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_skills_category_id"), "skills", ["category_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_skills_category_id_skill_categories"),
        "skills",
        "skill_categories",
        ["category_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_skills_category_id_skill_categories"), "skills", type_="foreignkey"
    )
    op.drop_index(op.f("ix_skills_category_id"), table_name="skills")
    op.drop_column("skills", "category_id")
    op.drop_table("skill_categories")
    # ### end Alembic commands ###
