"""add  server default uuid7 gen

Revision ID: 5af022d31e55
Revises: 4a3af0b4036e
Create Date: 2026-09-16 13:35:51.532410

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5af022d31e55"
down_revision: str | Sequence[str] | None = "4a3af0b4036e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        server_default=sa.text("uuidv7()"),
    )
    op.alter_column(
        "profiles",
        "id",
        server_default=sa.text("uuidv7()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        server_default=None,
    )
    op.alter_column(
        "profiles",
        "id",
        server_default=None,
    )
    # ### end Alembic commands ###
