"""create social links table

Revision ID: 5e4e1f5c5f4a
Revises: f956e7f2c428
Create Date: 2026-09-22 13:43:07.428156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4e1f5c5f4a'
down_revision: Union[str, Sequence[str], None] = 'f956e7f2c428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_social_links_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_links'))
    )
    op.create_index(op.f('ix_social_links_portfolio_id'), 'social_links', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_links_portfolio_id'), table_name='social_links')
    op.drop_table('social_links')
    # ### end Alembic commands ###
