"""create blog post tags table

Revision ID: 6cc3651a3cdc
Revises: 6ee1793a78b6
Create Date: 2026-09-22 16:39:51.612718

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cc3651a3cdc"
down_revision: str | Sequence[str] | None = "6ee1793a78b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_post_tags",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["blog_posts.id"],
            name=op.f("fk_blog_post_tags_post_id_blog_posts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("fk_blog_post_tags_tag_id_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_post_tags")),
    )
    op.create_index(
        op.f("ix_blog_post_tags_post_id"), "blog_post_tags", ["post_id"], unique=False
    )
    op.create_index(
        op.f("ix_blog_post_tags_tag_id"), "blog_post_tags", ["tag_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blog_post_tags_tag_id"), table_name="blog_post_tags")
    op.drop_index(op.f("ix_blog_post_tags_post_id"), table_name="blog_post_tags")
    op.drop_table("blog_post_tags")
    # ### end Alembic commands ###
