"""create portfolio settings table

Revision ID: 7f95897f8e9b
Revises: f5892f1575e9
Create Date: 2026-09-22 13:03:38.498558

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f95897f8e9b"
down_revision: str | Sequence[str] | None = "f5892f1575e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_settings",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("show_resume", sa.Boolean(), nullable=False),
        sa.Column("show_contact", sa.Boolean(), nullable=False),
        sa.Column("show_blog", sa.Boolean(), nullable=False),
        sa.Column("show_projects", sa.Boolean(), nullable=False),
        sa.Column("show_experience", sa.Boolean(), nullable=False),
        sa.Column("show_education", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_settings_portfolio_id_portfolios"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_settings")),
    )
    op.create_index(
        op.f("ix_portfolio_settings_portfolio_id"),
        "portfolio_settings",
        ["portfolio_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_portfolio_settings_portfolio_id"), table_name="portfolio_settings"
    )
    op.drop_table("portfolio_settings")
    # ### end Alembic commands ###
