"""create portfolio themes table

Revision ID: 8a5d70019e89
Revises: 7f95897f8e9b
Create Date: 2026-09-22 13:13:30.350132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5d70019e89'
down_revision: Union[str, Sequence[str], None] = '7f95897f8e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_themes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('template', sa.String(length=100), nullable=False),
    sa.Column('primary_color', sa.String(length=20), nullable=False),
    sa.Column('accent_color', sa.String(length=20), nullable=False),
    sa.Column('font_heading', sa.String(length=100), nullable=False),
    sa.Column('font_body', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_themes_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_themes'))
    )
    op.create_index(op.f('ix_portfolio_themes_portfolio_id'), 'portfolio_themes', ['portfolio_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_themes_portfolio_id'), table_name='portfolio_themes')
    op.drop_table('portfolio_themes')
    # ### end Alembic commands ###
