"""rename owner to user

Revision ID: 8f164e045b8a
Revises: 5ad6921bd617
Create Date: 2026-09-25 15:08:47.351076

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f164e045b8a"
down_revision: str | Sequence[str] | None = "5ad6921bd617"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("portfolios", sa.Column("user_id", sa.UUID(), nullable=False))
    op.drop_index(op.f("ix_portfolios_owner_id"), table_name="portfolios")
    op.create_index(
        op.f("ix_portfolios_user_id"), "portfolios", ["user_id"], unique=True
    )
    op.drop_constraint(
        op.f("fk_portfolios_owner_id_users"), "portfolios", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_portfolios_user_id_users"),
        "portfolios",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("portfolios", "owner_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "portfolios",
        sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_portfolios_user_id_users"), "portfolios", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_portfolios_owner_id_users"),
        "portfolios",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_portfolios_user_id"), table_name="portfolios")
    op.create_index(
        op.f("ix_portfolios_owner_id"), "portfolios", ["owner_id"], unique=True
    )
    op.drop_column("portfolios", "user_id")
    # ### end Alembic commands ###
