"""resolved blog post tag relationship

Revision ID: 919b34788513
Revises: 3afbe511ff20
Create Date: 2026-09-24 17:36:12.092406

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "919b34788513"
down_revision: str | Sequence[str] | None = "3afbe511ff20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
