"""create project technologies table

Revision ID: 9a5a04ef4c22
Revises: fcd17ea65a74
Create Date: 2026-09-22 15:50:35.741885

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a5a04ef4c22"
down_revision: str | Sequence[str] | None = "fcd17ea65a74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_technologies",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("technology_id", sa.UUID(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_technologies_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
            name=op.f("fk_project_technologies_technology_id_technologies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_technologies")),
    )
    op.create_index(
        op.f("ix_project_technologies_project_id"),
        "project_technologies",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_technologies_technology_id"),
        "project_technologies",
        ["technology_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_technologies_technology_id"), table_name="project_technologies"
    )
    op.drop_index(
        op.f("ix_project_technologies_project_id"), table_name="project_technologies"
    )
    op.drop_table("project_technologies")
    # ### end Alembic commands ###
