"""create portfolio seo table

Revision ID: e23215898bd6
Revises: 8a5d70019e89
Create Date: 2026-09-22 13:25:12.431582

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e23215898bd6"
down_revision: str | Sequence[str] | None = "8a5d70019e89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_seo",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("keywords", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("og_image_url", sa.String(length=1000), nullable=True),
        sa.Column("canonical_url", sa.String(length=1000), nullable=True),
        sa.Column("no_index", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_seo_portfolio_id_portfolios"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_seo")),
    )
    op.create_index(
        op.f("ix_portfolio_seo_portfolio_id"),
        "portfolio_seo",
        ["portfolio_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_portfolio_seo_portfolio_id"), table_name="portfolio_seo")
    op.drop_table("portfolio_seo")
    # ### end Alembic commands ###
