"""create portfolio sections table

Revision ID: f956e7f2c428
Revises: e23215898bd6
Create Date: 2026-09-22 13:34:46.072378

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f956e7f2c428"
down_revision: str | Sequence[str] | None = "e23215898bd6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_sections",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum(name="section_type"), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_sections_portfolio_id_portfolios"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_sections")),
    )
    op.create_index(
        op.f("ix_portfolio_sections_portfolio_id"),
        "portfolio_sections",
        ["portfolio_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_portfolio_sections_portfolio_id"), table_name="portfolio_sections"
    )
    op.drop_table("portfolio_sections")
    # ### end Alembic commands ###
